# Generated by Django 2.1.7 on 2019-03-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0002_auto_20190227_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.CharField(max_length=256)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='continuum.User')),
            ],
        ),
    ]
