# Generated by Django 2.1.7 on 2019-03-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0004_auto_20190301_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='project',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
