# Generated by Django 2.1.7 on 2019-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0005_auto_20190301_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='votes',
            field=models.CharField(max_length=255),
        ),
    ]
