# Generated by Django 2.1.7 on 2019-03-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0006_auto_20190301_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='project',
        ),
    ]
