# Generated by Django 2.1.7 on 2019-03-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0009_auto_20190301_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='question',
            name='budget',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
