# Generated by Django 2.1.7 on 2019-03-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0010_auto_20190301_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='choice',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
