# Generated by Django 2.1.7 on 2019-03-03 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0011_auto_20190303_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 20, 36, 36, 602426, tzinfo=utc), verbose_name='date published'),
        ),
    ]
