# Generated by Django 2.1.7 on 2019-03-04 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0015_auto_20190303_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continuum.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 12, 6, 38, 38697, tzinfo=utc), verbose_name='date published'),
        ),
    ]
