# Generated by Django 2.1.7 on 2019-03-04 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('continuum', '0017_auto_20190304_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 17, 58, 39, 112434, tzinfo=utc), verbose_name='date published'),
        ),
    ]
